server:
  port: 8080
  servlet:
    context-path: /currency

spring:
  application:
    name: currency-service
  datasource:
    url: jdbc:mysql://localhost:3306/currencies_db?useSSL=false&createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 1919
    driver-class-name: com.mysql.cj.jdbc.Driver
# JPA
  jpa:
    properties:
      ddl-auto: none
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: "TRUE"
    show-sql: true
# Flyway
  flyway:
    user: root
    password: 1919
    url: jdbc:mysql://localhost:3306/currencies_db

fixer:
  base:
    url: http://data.fixer.io/api
  api:
    key: 1044dc5ed8f8b4d8fa259794bbb38fcc
logging:
  level:
    org: INFO
