server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level: 
    org: INFO 

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/currencies_db?useSSL=false&createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 1919
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      ddl-auto: auto-update
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: "TRUE"
    show-sql: true