version: '3.3'

services:
  maria-db:
    container_name: maria-db
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: 'currencies_db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'root'
      # You can use whatever password you like
      MYSQL_PASSWORD: '1919'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '1919'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - maria-db:/var/lib/mysql
# Names our volume
volumes:
  maria-db: