openapi: 3.0.2
info:
  title: Currency API
  description: Api Documentation
  termsOfService: urn:tos
  contact: {}
  license:
    name: Eclipse Public License 2.0
    url: https://www.eclipse.org/legal/epl-2.0/
  version: '0.0.1-SNAPSHOT'

servers:
  - url: //127.0.0.1:8080/api/
tags:
  - name: Currency rate api
    description: Currency Rate Controler

paths:
  /rates//get-all:
    get:
      summary: Return all currency rates.
      #      parameters:
      #        - name: userId
      #          in: path
      #          required: true
      #          description: The ID of the user to return.
      #          schema:
      #            type: integer
      #            format: int64
      #            minimum: 1
      responses:
        200:
          description: List of currency rates.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CurrencyRate'
        400:
          description: The specified user ID is invalid (not a number).
        404:
          description: A user with the specified ID was not found.
        default:
          description: Unexpected error

components:
  schemas:
    CurrencyRate:
      properties:
        id:
          type: integer
          format: int64
        createdOn:
          type: string
          format: date-time
        base:
          type: string
        quoteName:
          $ref: '#/components/schemas/CurrencyQuoteName'
        rate:
          type: integer
          format: int64
        reverseRate:
          type: integer
          format: int64
        source:
          type: string
        sourceCreatedOn:
          type: string
          format: date-time
      required:
        - id
        - createdOn
        - base
        - quoteName
        - rate
    CurrencyQuoteName:
      properties:
        id:
          type: string
        name:
          type: string
        source:
          type: string
      required:
        - id
        - name
        - source