openapi: 3.0.2
info:
  title: Currency API
  description: Api Documentation
  termsOfService: urn:tos
  contact: { }
  license:
    name: Eclipse Public License 2.0
    url: https://www.eclipse.org/legal/epl-2.0/
  version: '0.0.1-SNAPSHOT'

servers:
  - url: //127.0.0.1:8080
tags:
  - name: Currency rate api
    description: Currency Rate Controler

paths:
  /rates:
    get:
      summary: Return all currency rates ordered by created date descending
      operationId: getAllRates
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CurrencyRate'
        400:
          description: Bad data
        404:
          description: Not found
        default:
          description: Unexpected error
    post:
      summary: Create currency rate and quote name
      operationId: createRate
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCurrencyRate'
      responses:
        201:
          description: Created
          content:
            text/plain:
              schema:
                type: string
        400:
          description: Bad data
        default:
          description: Unexpected error
  /rates/{rateId}:
    get:
      summary: Get currency rate for given Id
      operationId: getRate
      parameters:
        - name: rateId
          in: path
          description: rateId
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CurrencyRate'
        400:
          description: Bad data
        404:
          description: Not found
        default:
          description: Unexpected error
    put:
      summary: Update currency rate for given Id
      operationId: updateRate
      parameters:
        - name: rateId
          in: path
          description: rateId
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CurrencyRate'
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CurrencyRate'
        204:
          description: No Content
        400:
          description: Bad data
        404:
          description: Not found
        default:
          description: Unexpected error
    delete:
      summary: Delete currency rate for given Id
      operationId: deleteRate
      parameters:
        - name: rateId
          in: path
          description: rateId
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Ok
          content: { }
        400:
          description: Bad data
        404:
          description: Not found
        default:
          description: Unexpected error

components:
  schemas:
    CurrencyRate:
      properties:
        id:
          type: integer
          format: int64
        createdOn:
          type: string
          format: date-time
        base:
          type: string
        quoteName:
          $ref: '#/components/schemas/CurrencyQuoteName'
        rate:
          type: number
          format: currency
        reverseRate:
          type: number
          format: currency
        source:
          type: string
        sourceCreatedOn:
          type: string
          format: date-time
      required:
        - id
        - createdOn
        - base
        - quoteName
        - rate
        - reverseRate
    CreateCurrencyRate:
      properties:
        base:
          type: string
        quoteName:
          $ref: '#/components/schemas/CreateCurrencyQuoteName'
        rate:
          type: number
          format: currency
      required:
        - base
        - quoteName
        - rate
    CurrencyQuoteName:
      properties:
        id:
          type: string
        name:
          type: string
        source:
          type: string
      required:
        - id
        - name
        - source
    CreateCurrencyQuoteName:
      properties:
        id:
          type: string
        name:
          type: string
      required:
        - id
        - name