openapi: 3.0.2
info:
  title: Currency API
  description: Api Documentation
  termsOfService: urn:tos
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
  version: '1.0'
servers:
  - url: //127.0.0.1:8080/api/
#tags:
#  - name: Private Account
#    description: Private Account Controler
#  - name: Internal Account
#    description: Internal Account Controler

