openapi: 3.0.2
info:
  title: Currency API
  description: Api Documentation
  termsOfService: urn:tos
  contact: { }
  license:
    name: Eclipse Public License 2.0
    url: https://www.eclipse.org/legal/epl-2.0/
  version: '0.0.1-SNAPSHOT'

servers:
  - url: //127.0.0.1:8080
tags:
  - name: Currency rate api
    description: Currency Rate Controler

paths:
  /rates:
    get:
      summary: Return all currency rates.
      operationId: getAllRates
      responses:
        200:
          description: List of currency rates.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CurrencyRate'
        400:
          description: Bad data
        404:
          description: Not found
        default:
          description: Unexpected error
    post:
      summary: Create currency rates and quote name.
      operationId: createRate
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCurrencyRate'
      responses:
        201:
          description: Created
          content:
            text/plain:
              schema:
                type: string
        400:
          description: Bad data
        default:
          description: Unexpected error
#    post:
#      summary: Create new rate.
#            parameters:
#              - name: userId
#                in: path
#                required: true
#                description: The ID of the user to return.
#                schema:
#                  type: integer
#                  format: int64
#                  minimum: 1
#      responses:
#        200:
#          description: List of currency rates.
#          content:
#            application/json:
#              schema:
#                type: array
#                items:
#                  $ref: '#/components/schemas/CurrencyRate'
#        400:
#          description: Bad data
#        404:
#          description: Not found
#        default:
#          description: Unexpected error
components:
  schemas:
    CurrencyRate:
      properties:
        id:
          type: integer
          format: int64
        createdOn:
          type: string
          format: date-time
        base:
          type: string
        quoteName:
          $ref: '#/components/schemas/CurrencyQuoteName'
        rate:
          type: integer
          format: int64
        reverseRate:
          type: integer
          format: int64
        source:
          type: string
        sourceCreatedOn:
          type: string
          format: date-time
      required:
        - id
        - createdOn
        - base
        - quoteName
        - rate
    CreateCurrencyRate:
      properties:
        base:
          type: string
        quoteName:
          $ref: '#/components/schemas/CreateCurrencyQuoteName'
        rate:
          type: integer
          format: int64
      required:
        - base
        - quoteName
        - rate
    CurrencyQuoteName:
      properties:
        id:
          type: string
        name:
          type: string
        source:
          type: string
      required:
        - id
        - name
        - source
    CreateCurrencyQuoteName:
      properties:
        id:
          type: string
        name:
          type: string
      required:
        - id
        - name